name: sandec_tutorial
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fancy_bottom_navigation: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/sarapan_roti_bakar.jpg
    - img/gudeg.JPG
    - img/lontong_tuyuhan.jpg
    - img/sarapan_pancake.jpg
    - img/sarapan_nasi_pecel.jpg
    - img/nasi_gandul.jpg
    - img/nasi_goreng.jpg
    - img/pindang_patin.jpg
    - img/rendang.jpg
    - img/sate_klatak.jpg
    - img/soto_betawi.jpg
    - img/soto_kudus.jpg
    - img/sarapan_sandwich.jpg
    - img/sarapan_telur.jpg
    - img/sarapan_bubur_sumsum.jpg
    - img/sarapan_bubur_ayam.jpg
    - img/sop_klaten.jpg
    - img/nasi_bakar.jpg
    - img/des_almond_tofu.jpg
    - img/des_flumerry.jpg
    - img/des_kirschenplotzer.jpg
    - img/des_teler.jpg
    - img/des_es_doger.jpg
    - img/des_lupis.jpg
    - img/des_grass_jelly.jpg
    - img/des_es_campur.jpg
    - img/des_batik_cake.jpg
    - img/des_struffule.jpg
    - img/des_pizzelle.jpg
    - img/des_biscotti.jpg
    - img/des_pandoro.jpg
    - img/des_pavlova.jpg
    - img/des_es_krim.jpg
    - img/des_cocada.jpg
    - img/des_cajeta.jpg
    - img/des_ais_kacang.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
